Revert "[nrf52] add adc (#9321)"
This reverts commit 7a4738ec4ec1d75fa989fb1e417ea41d61033651.

ESP32-C6 does not compile with this commit.
End of the error message:
  File "/config/.esphome/external_components/bddf0801/esphome/components/adc/__init__.py", line 291, in <module>
    "adc_sensor_zephyr.cpp": {PlatformFramework.NRF52_ZEPHYR},
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'PlatformFramework' has no attribute 'NRF52_ZEPHYR'
Failed config

Platform not found: 'sensor.adc'